server:
  port: 8000
spring:
  application:
    name: Eureka_Server
eureka:
  instance:
    hostname: localhost
  client:
    # false表示自己端就是注册中心，职责就是维护服务实例，并不需要去检查服务
    fetch-registry: false
    # false表示不向注册中心注册自己
    register-with-eureka: false
    # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

