server:
  port: 8004
spring:
  application:
    name: Feign_Consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
#      开启Feign的Hystrix支持。
feign:
  hystrix:
    enabled: true